# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='land_profile',
            new_name='LandProfile',
        ),
    ]
