# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0004_soilmoisture'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilmoisture',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
